### ISSUE TITLE
12 drugs have duplicate entries

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/covid19_crowd_library#102]
**Describe the bug**
Received an e-mail from a user that found that 12 of the drugs have duplicate entries. See below:
mefloquine | 2 | 12, 10
convallatoxin | 2 | 1,1
loratadine | 2 | 1,1
bremelanotide | 2 | 1,1
pentagastrin | 2 | 1,1
adenosine triphosphate | 2 | 1,1
abemaciclib | 2 | 1,1
anidulafungin | 2 | 1,1
pyronaridine tetraphosphate | 2 | 1,1
tgx-115 | 2 | 1,1
lycopene | 2 | 1,1
torin-2 | 2 | 1,1

**To Reproduce**
Search for a drug from this list on the statistics page. There will be two drugs with the same name.

**Expected behavior**
One entry per drug.

**Comment by maxim-k** [comment]
It's a splitting problem.
First drug is 'mefloquine', and the second drug is 'mefloquine '

**Comment by maxim-k** [comment]
It's semi-reproducible - I found three drugs with trailing space and manually fixed it.
But I don't see what's wrong with other nine.
