### ISSUE TITLE
Platform is overwhelmed by too-frequent submissions that aren't overly frequent

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/covid19_crowd_library#109]
Avi informed me that my gene set submissions to this platform have been overwhelming the database. Before I saw his message, I had been submitting a series of gene sets, and after submitting 16 gene sets over a ~1-hour period, I finally received a 503 error when I tried to access the site. That error resolved within ~30 minutes, and I was able to finish submitting the remaining gene set.

On past days, I had similarly submitted large series of gene sets, and as far as I'm aware, there was no change from the past in the content or frequency of my submissions today. My concern is that it always takes at least ~1-3 minutes for me to prepare and submit a gene set, so I was surprised that the database wouldn't be able to handle this level of activity from a single user. Once the associated paper is published and this platform becomes much more widely used, I'm concerned that it might not be able to handle concurrent submissions from multiple users, if it is currently having issues handling a single user's submissions every few minutes or so.

I'll look forward to updates about this issue, because I'm currently unsure how much of a pause I'll need to insert between my submissions in order to avoid this issue in the future, and I'm also hesitant about having to take an artificially longer time to submit this data, since working as efficiently as possible would be ideal...

**Comment by maxim-k** [comment]
@KMJ1618, sorry for lost time and effort. I checked the logs and the database - you submitted on of lists at 9:00PM, and I deployed a new version at 9:44. So it was coincidence. Unfortunately, I'm not sure we can do better with downtime.
