### ISSUE TITLE
Warning message when access site via Chrome browser

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/covid19_crowd_library#111]
When I access this site via the Chrome browser, I see the attached warning message pop up. I can dismiss this message by clicking the "OK" button twice (the warning message refreshes after clicking the button the first time); however, I see that if I attempt to type or delete any characters into or from the search box, this message pops up again with each character that is typed, so the search feature isn't functional for me when using Chrome. Also, as in the past, the data tables are not visible.

Interestingly, I don't encounter these issues if I use the Firefox browser.

![COVID-19-CrowdsourcingSite_AppearanceOfSiteViaChrome_4-30-20](https://user-images.githubusercontent.com/7283504/80743584-30450a00-8aeb-11ea-8806-9c93e191247e.PNG)

**Comment by maxim-k** [comment]
I was fixing a bug and re-deploying a container
