### ISSUE TITLE
Is this URL right?

### ISSUE THREAD

**Issue by u8sand** [MaayanLab/covid19_crowd_library#125]
![image](https://user-images.githubusercontent.com/1341861/82369241-b49cf580-99e4-11ea-9f59-efdf4f4ba817.png)

**Comment by maxim-k** [comment]
@u8sand idk. This function https://github.com/MaayanLab/covid19_crowd_library/blob/abd9d1a9616c406888ee64c9237ca0905a36a30f/app/static/geneset.js#L13-L16 works for this input 
`Geneshot, keyword "SARS", method = GeneRIF ; https://amp.pharm.mssm.edu/geneshot/index.html?searchin=SARS&searchnot=&rif=generif` in console. But it doesn't work here https://github.com/MaayanLab/covid19_crowd_library/blob/abd9d1a9616c406888ee64c9237ca0905a36a30f/app/static/geneset.js#L51

Seems to be working on other URLs though

**Comment by u8sand** [comment]
@maxim-k yeah the problem is the url, not the urlify code. Valid urls have a query string `?key=value&...` but this one starts with `=`. In other word, this url is invalid, so perhaps your url validation could have detected this? Here is the url <https://amp.pharm.mssm.edu/geneshot/index.html=&rif=generif>  it also doesn't go anywhere..

**Comment by maxim-k** [comment]
@u8sand can't do `/^...$/`, because some of old sources are `Text URL text`.
Mysteriously it works now.
