### ISSUE TITLE
Info bubble disappearing too soon after next click

### ISSUE THREAD

**Issue by jessiecheng25** [MaayanLab/covid19_crowd_library#130]
Is there a way to make the info bubble for each submitted gene set stay open longer? It pops up when I click on the gene set name but I can’t actually copy/paste the links (in black) located within it since the bubble vanishes immediately with the next click.

**Comment by maxim-k** [comment]
Ideally it shouldn't close at all if you click on a popover. But that's bootstap's `focus` behavior (doesn't make much sense to me though) and changing it is hack~ish, and, probably, has side-effects. So I just increased delay to 4 seconds.
