### ISSUE TITLE
Enrichr appyter for gene sets from SARS-CoV-2 expression has errors and did not complete

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/covid19_crowd_library#145]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by u8sand** [comment]
I've fixed these.. some of these appyters were using the old version which **is not capable of handling many users**; I've migrated these..

**Comment by AviMaayan** [comment]
Thank you!
