### ISSUE TITLE
Import all SARS signatures from GEN3VA

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/covid19_crowd_library#21]
These should be up/down gene set separately

**Comment by maxim-k** [comment]
https://amp.pharm.mssm.edu/gen3va/report/644/SARS

**Comment by AviMaayan** [comment]
This one is more updated: https://amp.pharm.mssm.edu/gen3va/report/646/SARS

**Comment by maxim-k** [comment]
@KMJ1618 I've seen you input a lot of gene sets from GEN3VA. If it's finished, I can close this issue.

**Comment by KMJ1618** [comment]
@maxim-k @AviMaayan Yes, I added all 70 gene sets (35 up, 35 down) for this complete set of 35 GEN3VA signatures; I believe that you can close this issue.
