### ISSUE TITLE
Add statistics 

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/covid19_crowd_library#24]
Number of gene lists
Number of drug lists
Number of contributors
Number of affiliations
Number of unique genes
Number of unique drugs

Since these are all numbers, they can be listed on the landing page without the "Number of"

**Comment by u8sand** [comment]
Function made for:

- [x] Number of gene lists
- [x] Number of drug lists
- [ ] Number of contributors
- [ ] Number of affiliations
- [x] Number of unique genes
- [x] Number of unique drugs

**Comment by maxim-k** [comment]
Numbers of contributors/affiliations doesn't make much sense since there are only 3 authors that allowed sharing of their contact information.
