### ISSUE TITLE
Add visualization of the most frequently submitted genes and drugs in sets

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/covid19_crowd_library#34]
This could make it easier to determine which genes and drugs are really on the radar.

**Comment by u8sand** [comment]
Added functions for getting the top genes and top drugs from database. Visualization pending

**Comment by u8sand** [comment]
What type of visualization would we use for this?

**Comment by maxim-k** [comment]
Addressed in https://github.com/MaayanLab/covid19_crowd_library/commit/689b7e84f33e75756200cbdf95b77922f08805fa
