### ISSUE TITLE
Add ability to view and submit drug sets

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/covid19_crowd_library#37]
The site has a tab to view Drug Sets and a tab to Add Drug Set, but both tabs are greyed out and non-functional. I see that this issue was previously submitted and subsequently closed, but it is not yet resolved...

I checked this behavior using both Chrome and Firefox browsers.

**Comment by AviMaayan** [comment]
Max is still working on it. It is not ready.

**Comment by maxim-k** [comment]
Closing as it's WIP
