### ISSUE TITLE
Recognize URLs in 'Source'

### ISSUE THREAD

**Issue by maxim-k** [MaayanLab/covid19_crowd_library#50]

**Comment by u8sand** [comment]
Should also see about making sure the link doesn't fall out of the box. Potentially just make it clickable and truncate it

**Comment by maxim-k** [comment]
@u8sand I tried to truncate it to the base URL. To me it looks somewhat awkward. Also doesn't work well for our tools as our base URL is https://amp.pharm.mssm.edu/
Moreover, some sources are mixed text and URLs.
`word-wrap`/`overflow-wrap` breaks it fine, but don't work for Safari/IE.
