### ISSUE TITLE
Add user input validation against a list of known drugs.

### ISSUE THREAD

**Issue by bartala** [MaayanLab/covid19_crowd_library#61]
Cilizapril --> Cilazapril
Defroxamine--> Deferoxamine
Dipiverfin-->Dipivefrin

**Comment by AviMaayan** [comment]
Let's be careful with this since drug names are not standards and we don't want to limit entries if they don't map to a dictionary. For those entry that are mapped, we can provide links and additional information, but the unmapped ones should be allowed in.

**Comment by u8sand** [comment]
For now we're creating them as they come in, we can merge them based on synonyms at a later time
