### ISSUE TITLE
Resolved: Unable to submit gene sets

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/covid19_crowd_library#72]
Update: At the time that I posted the issue below, I hadn't been aware that each submission is manually reviewed before inclusion in this database. Therefore, the reported issue below can be considered as resolved.

I'm aware that clicking the Submit button yields no success message and does not clear the completed entry fields when submitting gene sets. However, even with that established, the gene sets that I'm submitting are still not being displayed in the gene set library on this platform. I tried submitting the example below twice, and have subsequently searched Gene Sets for "Geneshot" and "pangolin", but this entry isn't displayed in the gene set library table:

Gene Set Name: Pangolin 2 Literature-Associated Genes from Geneshot GeneRIF

Gene Set Source: Geneshot

How this set is related to COVID-19 research?

Pangolins, scaly anteaters, are hypthesized to possibly have transmitted coronavirus to humans:

Missing link in coronavirus jump from bats to humans could be pangolins, not snakes (3/26/2020)
https://www.sciencedaily.com/releases/2020/03/200326144342.htm

Mystery deepens over animal source of coronavirus (2/26/2020)
Pangolins are a prime suspect, but a slew of genetic analyses has yet to find conclusive proof.
https://www.nature.com/articles/d41586-020-00548-w

Gene Set:
LINS1
FAM83H

**Comment by AviMaayan** [comment]
@KMJ1618 once you submit. The list goes to a review pile and only added if approved.

**Comment by KMJ1618** [comment]
Ok, that's helpful to know; thanks for the clarification.
