### ISSUE TITLE
Change behavior when clicking on the numbers at the top of the landing page

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/covid19_crowd_library#79]
If clicking on # Drug Sets -> Go or stay on the landing page of the Drug Sets
If clicking on # Unique Drugs -> Go to the stats page that lists the drugs
If clicking on # Gene Sets -> Go or stay on the landing page of the Gene Sets
If clicking on # Unique Genes -> Go to the stats page that lists the genes

**Comment by u8sand** [comment]
I already did this, it will show up when max updates production

**Comment by maxim-k** [comment]
I almost gave up and rolled it back completely, but then I realized how can I use BOTH solutions.

**Comment by maxim-k** [comment]
Seemingly needs more testing/work
