### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/covid19_crowd_library#80]
As of ~10:50 pm, attempting to access this site yields the error message:

503 Service Unavailable
No server is available to handle this request.

This was the status for ~15+ minutes during which I repeatedly attempted to access this site; I didn't try again until ~2 hours later.

**Comment by KMJ1618** [comment]
Update, as of 1 am, 4/07/20: The website is now accessible again...

**Comment by maxim-k** [comment]
Oh it was me restarting it.
