### ISSUE TITLE
Add main descriptor to gene sets in genesets.gmt file

### ISSUE THREAD

**Issue by jlaw9** [MaayanLab/covid19_crowd_library#82]
Currently, the [genesets.gmt](https://amp.pharm.mssm.edu/covid19/genesets.gmt) file available by the "Download all gene sets" link often does not have enough information to identify the gene sets. It appears that the description that shows up when you click on a link is in the first column of the gmt file, and the main descriptor does not show up at all.

For example, currently the first gene set in the [gene sets table](https://amp.pharm.mssm.edu/covid19/#nav-genes-table) is "ACE2 Pathway from BioCarta 2013". If you click on the text in the description column, it shows "ACE2 is the likely point of entry for COVID-19. This list of from a BioCarta pathway from 2013." That popup text is what shows up in the gmt file in the first column: `44_ACE2 is the likely point of entry for COVID-19. This list of from a BioCarta pathway from 2013`. 

In some cases, only generic text was placed in the popup, making the gene set unidentifiable e.g., `71_SARS-CoV is the perturbagen used in this mouse study.`

The second column of the gmt file is empty. I believe the main descriptor was meant to be in the first column, and the popup text in the second. Is that the case? If so, could you please make that change?

Thank you in advance, and thank you so much for making this resource available!

**Comment by u8sand** [comment]
Seems reasonable
