### ISSUE TITLE
URL in the drug set landing page spills over

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/covid19_crowd_library#96]
**Describe the bug**
URL in the drug set landing page spills over

**To Reproduce**
1. click in the number of drugs

**Expected behavior**
URL fits in box or displayed in a pop-up

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maxim-k** [comment]
Duplicate of #50
